// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA10ee904FQkdVLZunNHVaFZBIePPLWKpY',
    appId: '1:288373616220:web:04b1d6cee78e7559ee4099',
    messagingSenderId: '288373616220',
    projectId: 'dicio-b9624',
    authDomain: 'dicio-b9624.firebaseapp.com',
    storageBucket: 'dicio-b9624.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB08NUd1dUSOOoCsuP0HIB0nBu9qNtDqkM',
    appId: '1:288373616220:android:df14c98eb786fe48ee4099',
    messagingSenderId: '288373616220',
    projectId: 'dicio-b9624',
    storageBucket: 'dicio-b9624.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe69wXpb_Ipp35PkLyoW0FPV9nc1ZMTY0',
    appId: '1:288373616220:ios:3517a86ead34cbcdee4099',
    messagingSenderId: '288373616220',
    projectId: 'dicio-b9624',
    storageBucket: 'dicio-b9624.appspot.com',
    iosBundleId: 'com.example.dicio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA10ee904FQkdVLZunNHVaFZBIePPLWKpY',
    appId: '1:288373616220:web:871b80d443bc3217ee4099',
    messagingSenderId: '288373616220',
    projectId: 'dicio-b9624',
    authDomain: 'dicio-b9624.firebaseapp.com',
    storageBucket: 'dicio-b9624.appspot.com',
  );
}
